[package]
name = "rgo-core"
description = "rgo library: config, storage paths, physical size accounting, contexts, GC, leases"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rgo-protocol.workspace = true
rgo-cas.workspace = true
rgo-remote.workspace = true
blake3.workspace = true
anyhow.workspace = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
toml_edit.workspace = true
tracing.workspace = true
humantime.workspace = true
bytesize.workspace = true
directories.workspace = true
walkdir.workspace = true
fs4.workspace = true
rustix.workspace = true
rusqlite.workspace = true
interprocess.workspace = true

[dev-dependencies]
tempfile.workspace = true
roxmltree = "0.21.1"

[target.'cfg(windows)'.dependencies]
roxmltree = "0.21.1"
rgo-winpipe.workspace = true

[lints]
workspace = true
